import streamDeck from "@elgato/streamdeck";
import { Headlights } from "./actions/headlights";
import { FlashLights } from "./actions/flash-lights";
import { RainLights } from "./actions/rain-lights";
import { WipersUp } from "./actions/wipers-up";
import { WipersDown } from "./actions/wipers-down";
import { Ignition } from "./actions/ignition";
import { Starter } from "./actions/starter";
import { PitLimiter } from "./actions/pit-limiter";
import { Horn } from "./actions/horn";
import { Drs } from "./actions/drs";
import { Kers } from "./actions/kers";
import { BbFront } from "./actions/bb-front";
import { BbRear } from "./actions/bb-rear";
import { TcIncrease } from "./actions/tc-increase";
import { TcDecrease } from "./actions/tc-decrease";
import { AbsIncrease } from "./actions/abs-increase";
import { AbsDecrease } from "./actions/abs-decrease";
import { EngineMapUp } from "./actions/engine-map-up";
import { EngineMapDown } from "./actions/engine-map-down";
import { GlanceLeft } from "./actions/glance-left";
import { GlanceRight } from "./actions/glance-right";
import { LookBehind } from "./actions/look-behind";
import { FreeCamera } from "./actions/free-camera";
import { TrackCamera } from "./actions/track-camera";
import { ChaseCamera } from "./actions/chase-camera";
import { VirtualMirror } from "./actions/virtual-mirror";
import { HudToggle } from "./actions/hud-toggle";
import { Leaderboard } from "./actions/leaderboard";
import { DamageDisplay } from "./actions/damage-display";
import { IdealLine } from "./actions/ideal-line";
import { AiTakeover } from "./actions/ai-takeover";
import { PitRequest } from "./actions/pit-request";
import { RestartSession } from "./actions/restart-session";
import { Replay } from "./actions/replay";
import { SlowMotion } from "./actions/slow-motion";
import { FastForward } from "./actions/fast-forward";
import { Rewind } from "./actions/rewind";
import { Screenshot } from "./actions/screenshot";
import { NextCar } from "./actions/next-car";
import { PrevCar } from "./actions/prev-car";
import { Pause } from "./actions/pause";

// streamDeck.logger.setLevel("DEBUG");

streamDeck.actions.registerAction(new Headlights());
streamDeck.actions.registerAction(new FlashLights());
streamDeck.actions.registerAction(new RainLights());
streamDeck.actions.registerAction(new WipersUp());
streamDeck.actions.registerAction(new WipersDown());
streamDeck.actions.registerAction(new Ignition());
streamDeck.actions.registerAction(new Starter());
streamDeck.actions.registerAction(new PitLimiter());
streamDeck.actions.registerAction(new Horn());
streamDeck.actions.registerAction(new Drs());
streamDeck.actions.registerAction(new Kers());
streamDeck.actions.registerAction(new BbFront());
streamDeck.actions.registerAction(new BbRear());
streamDeck.actions.registerAction(new TcIncrease());
streamDeck.actions.registerAction(new TcDecrease());
streamDeck.actions.registerAction(new AbsIncrease());
streamDeck.actions.registerAction(new AbsDecrease());
streamDeck.actions.registerAction(new EngineMapUp());
streamDeck.actions.registerAction(new EngineMapDown());
streamDeck.actions.registerAction(new GlanceLeft());
streamDeck.actions.registerAction(new GlanceRight());
streamDeck.actions.registerAction(new LookBehind());
streamDeck.actions.registerAction(new FreeCamera());
streamDeck.actions.registerAction(new TrackCamera());
streamDeck.actions.registerAction(new ChaseCamera());
streamDeck.actions.registerAction(new VirtualMirror());
streamDeck.actions.registerAction(new HudToggle());
streamDeck.actions.registerAction(new Leaderboard());
streamDeck.actions.registerAction(new DamageDisplay());
streamDeck.actions.registerAction(new IdealLine());
streamDeck.actions.registerAction(new AiTakeover());
streamDeck.actions.registerAction(new PitRequest());
streamDeck.actions.registerAction(new RestartSession());
streamDeck.actions.registerAction(new Replay());
streamDeck.actions.registerAction(new SlowMotion());
streamDeck.actions.registerAction(new FastForward());
streamDeck.actions.registerAction(new Rewind());
streamDeck.actions.registerAction(new Screenshot());
streamDeck.actions.registerAction(new NextCar());
streamDeck.actions.registerAction(new PrevCar());
streamDeck.actions.registerAction(new Pause());

streamDeck.connect();
